// This file will be auto-generated by Supabase CLI
// For now, we'll create a basic type structure

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          username: string | null;
          display_name: string | null;
          avatar_url: string | null;
          role: string;
          status: string;
          bitcoin_address: string | null;
          lightning_address: string | null;
          bio: string | null;
          location: string | null;
          website: string | null;
          steam_id: string | null;
          theme: string;
          language: string;
          currency: string;
          notifications_email: boolean;
          notifications_push: boolean;
          notifications_game_updates: boolean;
          notifications_friend_activity: boolean;
          notifications_promotions: boolean;
          privacy_show_online_status: boolean;
          privacy_show_game_activity: boolean;
          privacy_allow_friend_requests: boolean;
          games_owned: number;
          total_hours_played: number;
          achievements_unlocked: number;
          friends_count: number;
          reviews_written: number;
          created_at: string;
          updated_at: string;
          last_login_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          username?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          status?: string;
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          bio?: string | null;
          location?: string | null;
          website?: string | null;
          steam_id?: string | null;
          theme?: string;
          language?: string;
          currency?: string;
          notifications_email?: boolean;
          notifications_push?: boolean;
          notifications_game_updates?: boolean;
          notifications_friend_activity?: boolean;
          notifications_promotions?: boolean;
          privacy_show_online_status?: boolean;
          privacy_show_game_activity?: boolean;
          privacy_allow_friend_requests?: boolean;
          games_owned?: number;
          total_hours_played?: number;
          achievements_unlocked?: number;
          friends_count?: number;
          reviews_written?: number;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          username?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          status?: string;
          bitcoin_address?: string | null;
          lightning_address?: string | null;
          bio?: string | null;
          location?: string | null;
          website?: string | null;
          steam_id?: string | null;
          theme?: string;
          language?: string;
          currency?: string;
          notifications_email?: boolean;
          notifications_push?: boolean;
          notifications_game_updates?: boolean;
          notifications_friend_activity?: boolean;
          notifications_promotions?: boolean;
          privacy_show_online_status?: boolean;
          privacy_show_game_activity?: boolean;
          privacy_allow_friend_requests?: boolean;
          games_owned?: number;
          total_hours_played?: number;
          achievements_unlocked?: number;
          friends_count?: number;
          reviews_written?: number;
          created_at?: string;
          updated_at?: string;
          last_login_at?: string | null;
        };
      };
      games: {
        Row: {
          id: string;
          title: string;
          developer: string;
          publisher: string;
          description: string;
          short_description: string;
          price_usd: number;
          price_btc: number;
          price_sats: number;
          discount_percent: number;
          genres: string[];
          tags: string[];
          rating: string;
          status: string;
          release_date: string;
          last_updated: string;
          header_image: string;
          screenshots: string[];
          videos: string[];
          logo: string | null;
          system_requirements_minimum: any;
          system_requirements_recommended: any;
          features: string[];
          languages: string[];
          total_achievements: number;
          positive_reviews: number;
          negative_reviews: number;
          review_score: number;
          file_size: string;
          version: string;
          created_at: string;
          updated_at: string;
        };
        Insert: any;
        Update: any;
      };
      // Add other tables as needed
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      search_games: {
        Args: {
          search_term?: string;
          genre_filter?: string;
          max_price_usd?: number;
          sort_by?: string;
          sort_order?: string;
        };
        Returns: any[];
      };
      get_user_library: {
        Args: {
          user_uuid: string;
        };
        Returns: any[];
      };
      get_user_stats: {
        Args: {
          user_uuid: string;
        };
        Returns: any[];
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
